AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  daily-checkers

  Sample SAM Template for daily-checkers

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  # API Gateway ------ API Gateway ------ API Gateway ------ API Gateway ------ API Gateway ------ API Gateway ------ API Gateway ------ API Gateway ------ API Gateway ------

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "1"
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          UserAuth:
            FunctionArn: !GetAtt UserAuth.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0
          VictorAuth:
            FunctionArn: !GetAtt VictorAuth.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0
  
  # Authorizers ------ Authorizers ------ Authorizers ------ Authorizers ------ Authorizers ------ Authorizers ------ Authorizers ------ Authorizers ------ Authorizers ------
  
  UserAuth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/user-auth/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable

  VictorAuth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/victor-auth/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable

  # Dynamo Tables ------ Dynamo Tables ------ Dynamo Tables ------ Dynamo Tables ------ Dynamo Tables ------ Dynamo Tables ------ Dynamo Tables ------ Dynamo Tables ------

  GameTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: DailyCheckers_Games_SAM
  
  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: DailyCheckers_Users_SAM
  
  InviteTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: DailyCheckers_Invites_SAM
  
  NotificationTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: DailyCheckers_Notifications_SAM
  
  # SQS ------ SQS ------ SQS ------ SQS ------ SQS ------ SQS ------ SQS ------ SQS ------ SQS ------

  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-queue

  # Lambdas (non-endpoints) ------ Lambdas (non-endpoints) ------ Lambdas (non-endpoints) ------ Lambdas (non-endpoints) ------ Lambdas (non-endpoints) ------
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedule.html

  ScheduledEmailSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: email/scheduled-sender/
      Handler: app.lambda_handler
      Runtime: python3.12
      Events:
        ScheduleEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(1 hour)"
      Environment:
        Variables:
          SMTP_HOST: smtp.ethereal.email
          SMTP_PORT: 587
          SMTP_USERNAME: isaac.lind93@ethereal.email
          SMTP_PASSWORD: 6BSWcnhBA8TpVg1TwJ
          SMTP_NAME: Isaac Lind
    
  QueuedEmailSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: email/queue-sender/
      Handler: app.lambda_handler
      Runtime: python3.12
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 1
      Environment:
        Variables:
          SMTP_HOST: smtp.ethereal.email
          SMTP_PORT: 587
          SMTP_USERNAME: isaac.lind93@ethereal.email
          SMTP_PASSWORD: 6BSWcnhBA8TpVg1TwJ
          SMTP_NAME: Isaac Lind
      Policies:
        - AmazonSQSFullAccess

  # Endpoints ------ Endpoints ------ Endpoints ------ Endpoints ------ Endpoints ------ Endpoints ------ Endpoints ------ Endpoints ------ Endpoints ------ 

  GameConcedeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/game-concede/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        ConcedeGame:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /game/concede/{id}
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref GameTable
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
        - AmazonSQSFullAccess

  GameTakeTurnFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/game-take-turn/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        GameTakeTurn:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /game/take-turn/{id}
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref GameTable
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
        - AmazonSQSFullAccess
  
  GameViewFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/game-view/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        GameView:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /game/view/{id}
            Method: get
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref GameTable
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
  
  GameListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/game-list/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        GameList:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /game/list
            Method: get
            Auth:
              Authorizer: UserAuth
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref GameTable
  
  InviteCreateFunction:
    Type: AWS::Serverless::Function #
    Properties:
      CodeUri: api/invite-create/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        InviteCreate:
          Type: Api # More info about API Event Source:
          Properties:
            RestApiId: !Ref MyApi
            Path: /invite
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref GameTable
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
        - AmazonSQSFullAccess
  
  InviteAcceptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/invite-accept/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        InviteAccept:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /invite/accept/{id}
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref GameTable
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
        - AmazonSQSFullAccess

  InviteDeclineFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/invite-decline/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        InviteDecline:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /invite/decline/{id}
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref GameTable
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
  
  InviteListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/invite-list/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        InviteList:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /invite/list
            Method: get
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref GameTable
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
  
  UserDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user-delete/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        UserDelete:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/delete/{id}
            Method: delete
            Auth:
              Authorizer: UserAuth
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref GameTable
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
        - AmazonSQSFullAccess

  UserRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user-register/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        UserRegister:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/register
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
        - AmazonSQSFullAccess
  
  UserUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user-update/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        UserUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/update/{id}
            Method: put
            Auth:
              Authorizer: UserAuth
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
        - AmazonSQSFullAccess

  UserUpdateCustomizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user_customization-update/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        UserUpdatePieces:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/update-customization/{id}
            Method: put
            Auth:
              Authorizer: VictorAuth
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable

  UserViewFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user-view/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        UserView:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/view/{id}
            Method: get
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable
  
  UserLogInFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/user-login/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Events:
        UserLogIn:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /user/login
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess
        - DynamoDBCrudPolicy:
            TableName: 
              !Ref UserTable